apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: atsea
  labels:
    app: atsea-db
type: Opaque
data:
  # base64 encoded values
  # echo -n "gordonuser" | base64 => Z29yZG9udXNlcg==
  # echo -n "atsea" | base64      => YXRzZWE=
  # echo -n "gordonpass" | base64  => Z29yZG9ucGFzcw==
  POSTGRES_USER: Z29yZG9udXNlcg==
  POSTGRES_DB: YXRzZWE=
  POSTGRES_PASSWORD: Z29yZG9ucGFzcw==
---
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: db-secret
#   namespace: atsea
# spec:
#   refreshInterval: 1h            # Auto-refreshes every hour
#   secretStoreRef:
#     name: aws-secrets-manager
#     kind: ClusterSecretStore
#   target:
#     name: db-secret              # Creates a K8s Secret automatically
#   data:
#     - secretKey: POSTGRES_PASSWORD
#       remoteRef:
#         key: prod/atsea/db       # Path in AWS Secrets Manager
#         property: password
