apiVersion: v1
kind: Secret
metadata:
  name: payment-gateway-secret
  namespace: atsea
  labels:
    app: atsea-payment-gateway
type: Opaque
data:
  # echo -n "staging" | base64 => c3RhZ2luZw==
  # For production, use: echo -n "production" | base64 => cHJvZHVjdGlvbg==
  payment_token: c3RhZ2luZw==
---
